version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: 'com.puppycrawl.tools:checkstyle'
        update-types: ['version-update:semver-major']
      - dependency-name: 'org.junit.jupiter:junit-jupiter'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'pip'
    directory: '/applications/generate'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 14
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 14
